import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pigeon Go</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Let us build the app</h1>

    </div>
  )
}
